[package]
name = "shady"
version = "0.1.0"
authors = ["Mike Sampson <mike@sambodata.com>"]
license = "MIT"
edition = "2018"

[dependencies]
image = "*"
glium = "0.27.0"
time = "0.2.16"
notify = "4.0.15"
